name: Run Reminder Scheduler

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 8:30 AM IST (03:00 UTC)
  workflow_dispatch:      # Allows manual run from GitHub

jobs:
  send_reminders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run reminder script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python reminder_scheduler.py
